# Site Info
title:              "Chen, Baoyi"
description:        "疯言讽语"
#google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-101913308-1 # Put your Google Analytics code

# Author Info
author_name:        "Chen, Baoyi" # Your name here
author_email:       baoyi@tapir.caltech.edu # Your email here
author_gravatar:    aa7de0338e677aceb92865b32724959b # Your Gravatar md5 hash here for logo
twitter_username:   hughug2333 # Your Twitter username here
github_username:    hughug # Your GitHub username here

# Site Settings
baseurl:            /blog # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  
remote_theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"


 

